services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${SERVICE_USER_POSTGRES:-postgres}
      POSTGRES_PASSWORD: ${SERVICE_PASSWORD_POSTGRES:-password}
      POSTGRES_DB: certificados
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # ports:
      # - "5432:5432"

  backend:
    build: ./app

    environment:
      NODE_ENV: production
    depends_on:
      - db

volumes:
  postgres-data: {}